### example 1

In [2]:
import numpy as np

A = np.array([[108.55, 20.3],
              [20.3, 4.]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

[[108.55  20.3 ]
 [ 20.3    4.  ]]
[[ 0.18091361 -0.91813659]
 [-0.91813659  4.90954319]]


In [5]:
# check
np.set_printoptions(suppress=True)

print(A.dot(A_inversed))
print(A_inversed.dot(A))

[[ 1. -0.]
 [ 0.  1.]]
[[ 1. -0.]
 [-0.  1.]]


### example 2

In [6]:
import numpy as np

A = np.array([[1, 2],
              [4, 6]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

[[1 2]
 [4 6]]
[[-3.   1. ]
 [ 2.  -0.5]]


In [7]:
# check
print(A.dot(A_inversed))
print(A_inversed.dot(A))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


### example 3

In [8]:
import numpy as np

A = np.array([[1, 0, 4],
              [0, 1, 2],
              [0, -3, -4]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

[[ 1  0  4]
 [ 0  1  2]
 [ 0 -3 -4]]
[[ 1.  -6.  -2. ]
 [-0.  -2.  -1. ]
 [ 0.   1.5  0.5]]


In [9]:
# check
print(A.dot(A_inversed))
print(A_inversed.dot(A))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
