In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
height, width, channel = img.shape
print(height, width, channel)
print(img.dtype)

cv2.imwrite('output.jpg', img)

500 1200 3
uint8


True

### Increate brightness

In [12]:
data = np.array([-4, 3, 8, 300, 7])
print(data)

data = np.clip(data, 0, 255)
print(data)

[ -4   3   8 300   7]
[  0   3   8 255   7]


In [8]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img + 50
img = np.clip(img, 0, 255)

img = img.astype(np.uint8)
cv2.imwrite('increase50_clip.jpg', img)

True

In [19]:
data = np.array([-4., 3, 8, 300, 7])
print(data)
print(data.dtype)

data = np.where(data<0, 0, data)
print(data)

data = np.where(data>255, 255, data)
print(data)

[ -4.   3.   8. 300.   7.]
float64
[  0.   3.   8. 300.   7.]
[  0.   3.   8. 255.   7.]


In [23]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img + 50
img = np.where(img<0., 0., img)
img = np.where(img>255., 255., img)

img = img.astype(np.uint8)
cv2.imwrite('increase50_where.jpg', img)

float64


True

### Decrease brightness

In [24]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img - 80
img = np.clip(img, 0, 255)

img = img.astype(np.uint8)
cv2.imwrite('decrease80_clip.jpg', img)

True

In [25]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img - 80
img = np.where(img<0., 0., img)
img = np.where(img>255., 255., img)

img = img.astype(np.uint8)
cv2.imwrite('decrease80_where.jpg', img)

True

### Flipping

In [56]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)
height, width, depth = img.shape

transform = np.array([[1, 0],
                      [0, -1]])

output = np.zeros((height, width, depth))
for i in range(height):
    for j in range(width):
        pixel = img[i, j, :]
        
        new_j, new_i = transform.dot(np.array([j, i])) 
                       + [0, height-1]
        output[new_i, new_j, :] = pixel
        
output = output.astype(np.uint8)
cv2.imwrite('flipping_x.jpg', output)

True

In [57]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)
height, width, depth = img.shape

transform = np.array([[-1, 0],
                      [0, 1]])

output = np.zeros((height, width, depth))
for i in range(height):
    for j in range(width):
        pixel = img[i, j, :]        
        new_j, new_i = transform.dot(np.array([j, i])) 
                       + [width-1, 0]
        output[new_i, new_j, :] = pixel
        
output = output.astype(np.uint8)
cv2.imwrite('flipping_y.jpg', output)

True

### Convert to grayscale

In [63]:
import cv2
import numpy as np

img = cv2.imread('nature.jpg', 1)
transform = np.array([0.072, 0.213, 0.715])

output = img@transform
cv2.imwrite('nature_grayscale_1.jpg', output)

True

In [64]:
import cv2
import numpy as np

img = cv2.imread('nature.jpg', 1)
transform = np.array([0.072, 0.213, 0.715])

output = img.dot(transform)
cv2.imwrite('nature_grayscale_2.jpg', output)

True

### Draw BB

In [1]:
data = [6, 5, 7, 1, 9, 2]
print(data)
data[1] = 4
print(data)

[6, 5, 7, 1, 9, 2]
[6, 4, 7, 1, 9, 2]


In [3]:
import numpy as np

data = np.array([6, 5, 7, 1, 9, 2])
print(data)

data[1] = 4
print(data)

[6 5 7 1 9 2]
[6 4 7 1 9 2]


In [4]:
data = [4, 5, 6, 7, 8, 9]
print(data)
data[0:3] = [1, 1, 1]
print(data)

[4, 5, 6, 7, 8, 9]
[1, 1, 1, 7, 8, 9]


In [5]:
import numpy as np

data = np.array([6, 5, 7, 1, 9, 2])
print(data)

data[0:3] = [1, 1, 1]
print(data)

[6 5 7 1 9 2]
[1 1 1 1 9 2]


In [6]:
import numpy as np

data = np.array([6, 5, 7, 1, 9, 2])
print(data)

data[0:3] = 1
print(data)

[6 5 7 1 9 2]
[1 1 1 1 9 2]


In [14]:
import cv2
import numpy as np

img = cv2.imread('image.jpg', 1)
height, width, channel = img.shape

left_x, left_y = 120, 470
right_x, right_y = 850, 800
color = np.array([0, 0, 255]).reshape(1, 3)

img[left_x, left_y:right_y, :] = color
img[right_x, left_y:right_y, :] = color

img[left_x:right_x, left_y, :] = color
img[left_x:right_x, right_y, :] = color

cv2.imwrite('output_bb.jpg', img)

True

### Crop a region

In [13]:
import cv2
import numpy as np

img = cv2.imread('image.jpg', 1)
height, width, channel = img.shape

left_x, left_y = 120, 470
right_x, right_y = 850, 800

region = img[left_x:right_x, left_y:right_y, :]
cv2.imwrite('output_region.jpg', region)

True