In [ ]:
import numpy as np
def computeVectorLength(vector):
    # ************* Your code *****************
  return len_of_vector


In [ ]:
### Question 1
vector = np.array([-2, 4, 9, 21])
result = computeVectorLength([vector])
print(round(result,2))

23.28


In [ ]:
def computeDotProduct(vector1, vector2):
  # ************* Your code *****************
  return result

In [ ]:
### Question 2
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = computeDotProduct(v1, v2)
print(round(result,2))

4


In [ ]:
### Question 3

x = np.array([[1, 2],
              [3, 4]])
k = np.array([1, 2])
print('result  \n', computeDotProduct(x, k))
print('result 1 \n', x.dot(k))

result  
 [ 5 11]
result 1 
 [ 5 11]


In [ ]:
### Question 4

x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [ ]:
def matrix_multi_vector(matrix, vector):
    # ************* Your code *****************
  return result

In [ ]:
### Question 5
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [ ]:
def matrix_multi_matrix(matrix1, matrix2):
    # ************* Your code ****************
  return result

In [ ]:
### Question 6
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [ ]:
### Question 7
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],[2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
### Question 8
m1 = np.eye(2)
m1 = np.reshape(m1,(-1,4))[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [ ]:
### Question 9
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1,(-1,4), "F")[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[29 29 29 29]


In [ ]:
def inverse_matrix(matrix):
  # ************* Your code *****************
  return result

In [ ]:
### Question 10
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [ ]:
def compute_eigenvalues_eigenvectors(matrix):
    # ************* Your code *****************
  return eigenvalues,eigenvectors

In [ ]:
### Question 11
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)


[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def compute_cosine(v1, v2):
    # ************* Your code *****************

  return cos_sim

In [ ]:
### Question 12
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))


0.577
